{":b:inky"          "imgur gYWlrwp"
 "binky"            "imgur gYWlrwp"
 "ink"              "imgur gYWlrwp"
 "inky"             "imgur gYWlrwp"
 "tripod"           "imgur gYWlrwp"

 ":bongo_silence:"  "imgur HJAUs1m"
 "silence"          "imgur HJAUs1m"
 "silenec"          "imgur HJAUs1m"

 ":opomuc:"         "imgur 5m8iBZq"
 "cefur"            "imgur 5m8iBZq"
 "muc"              "imgur 5m8iBZq"
 "muuc"             "imgur 5m8iBZq"
 "muuuc"            "imgur 5m8iBZq"
 "muuuuc"           "imgur 5m8iBZq"
 "muuuuuc"          "imgur 5m8iBZq"
 "muuuuuuc"         "imgur 5m8iBZq"
 "muuuuuuuc"        "imgur 5m8iBZq"
 "muuuuuuuuc"       "imgur 5m8iBZq"
 "muuuuuuuuuc"      "imgur 5m8iBZq"
 "muuuuuuuuuuc"     "imgur 5m8iBZq"
 "muuuuuuuuuuuc"    "imgur 5m8iBZq"
 "opomuc"           "imgur 5m8iBZq"

 "ciri"             "imgur FLOxSG3"
 "cric"             "imgur FLOxSG3"
 "cricek"           "imgur FLOxSG3"
 "nichi"            "imgur FLOxSG3"

 "satan"            "imgur nVCMPIl"
 "stan"             "imgur nVCMPIl"}
